### ISSUE TITLE
Early to-dos

### ISSUE THREAD

**Issue by dansbecker** [dansbecker/motion-tracking#17]
- [x] Get model running on AWS (fix Makefile)
- [x] Refactor generators to classes
- [x] Move convolutional part of model closer to AlexNet (basically, make it bigger)
- [x] Visualize output (show image with predicted and true bounding box
- [x] Track down resize errors
- [ ] Validation data and potentially other data sources
- [ ] Visualization of weights / activations
- [ ] Visualize training with Tensorboard

**Comment by sallamander** [comment]
- [x] Refactor `crop_vis.py` (before visualize output - forgot we needed to do this last night, but it should be easy)
